config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#index"
  resource :pages
  get "front_end_testing", to: "pages#front_end_testing", as: "front_end_testing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # before_action :authenticate_user!

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base

    def index
        render layout: "application"
    end

    def new
        @page = Page.new
        render layout: "application"
    end

    def create
        Page.create!(page_params)
        
        redirect_to root_path
    end


    private
    def page_params
        params.require(:title).permit(:page_url, :page_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tristate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- jquery UI -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js" integrity="sha256-xNjb53/rY+WmG+4L6tTl9m6PpqknWZvRt0rO1SRnJzw=" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/c345e56eb7.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
      <%#= render partial: "layouts/shared/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_flash_messages.html.erb
<% if alert %>
<div class="application-notification">
 <div class="alert">
   <%= alert %>
 </div>
</div>
<% end %>

<% if notice %>
 <div class="application-notification">
   <div class="notice">
     <%= notice %>
   </div>
 </div>
<% end %>

app/views/pages/front_end_testing.html.erb
<%= content_tag :h1, "Welcome To Front End Testing"%>

app/views/pages/index.html.erb
<%= content_tag :h1, "Welcome Home", class:""%>
<div id="test">
    <h2><%= link_to "Go To Front End Testing", front_end_testing_path %></h2>
    <% if user_signed_in?%>
        <h2>User: <%= current_user.email %></h2>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <%else%>
        <%= link_to "Sign In", new_user_session_path%><br>
        <%= link_to "Sign Up", new_user_registration_path %><br>
    <%end%>
</div>

app/views/pages/new.html.erb
<%= content_tag :h1, "Create a new page"%>
<%= form_for :page, url: pages_path do |f| %>
    <div class="form-group">
        <%= f.label :title, "Page Title", class: "control-label" %>
        <%= f.text_field :title, required: true, class:"form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :page_url, "Page Url", class: "control-label" %>
        <%= f.text_field :page_url, required: true, class:"form-control"%>
    </div>

    <div class="form-group">
        <%= f.label :id, "Page ID", class: "control-label" %>
        <%= f.number_field :page_id, required: true, class:"form-control" %>
    </div>
    <%= f.submit "Create Page", class: "btn btn-primary" %>
<%end%>